name: UnicomTask

on:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
    - cron: 30 22 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Setup pytools
        run: |
          curl -O https://raw.githubusercontent.com/w311ang/pytools/main/pytools.py
          curl -O https://raw.githubusercontent.com/w311ang/pytools/main/aes.py
          pip install PyCryptodome
      - name: Set proxy
        uses: w311ang/setproxy@main
        with:
          config: ${{ secrets.ss_config }}
      - name: Config
        env: 
          config: ${{ secrets.config }}
        run: |
          echo "$config"|base64 -d > ./config.json
      - name: Run
        env:
          jmail: ${{ secrets.jmail }}
        run: |
          proxychains python -u index.py
